package KieRule;
import com.arocruz8.spring.drools.api.Order;

rule "BancoNacional"

when
orderObject : Order(cardType=="BancoNacional" && price>=10000);
then
orderObject.setDiscount(10);
end;

rule "BancoPopular"

when
orderObject : Order(cardType=="BancoPopular" && price<8000);
then
orderObject.setDiscount(8);
end;

rule "BCR"

when
orderObject : Order(cardType=="BCR" && price>5000);
then
orderObject.setDiscount(5);
end;